server:
  port: 8086

spring:
  application:
    name: customer-details-service
  datasource:
    url: jdbc:postgresql://localhost:5436/customer_db?TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.bookstore.customer