spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: bookstore-super-secret-key-must-be-long-enough-256bits
  expiry: 86400000